name: snyk security scan
run-name: SNYK security scan for '${{ github.ref }}'

on: [push]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:

  SNYK:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@master

      - uses: snyk/actions/setup@master

      - name: Generate code vulnerability report
        id: run_snyk
        run: |
          snyk code test --project-name="${{ github.repository }}" --report ${{ github.workspace }}
        continue-on-error: true
